name: Deploy Static Next.js via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build and Export Static Site
        run: |
          npm run build
          npm run export

      - name: Upload via FTP
        uses: git-ftp/action@v5
        with:
          url: ftp://${{ secrets.FTP_HOST }}/${{ secrets.FTP_TARGET_DIR }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out
