name: Deploy Static Next.js to Dewaweb via FTP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build and Export Static Site
        run: |
          npm run build
          npm run export

      - name: Upload to FTP Server
        uses: sebastianpopp/ftp-action@v1.2.0
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: ./out
          remoteDir: ${{ secrets.FTP_TARGET_DIR }}
